awslabs/aws-healthomics-tools

- .gitignore
- Makefile
- README.md
- poetry.lock
- pyproject.toml
* Add license, description, and repository properties for display on PyPI
* Bump version to `0.1.1` in preparation for publishing
* Switch dependencies to the public versions of `boto3` and `mypy-boto3-omics`
> Add description for PyPI and bump version for release

- pyproject.toml
*Issue #, if available:* N/A
*Description of changes:* Bumping version to 0.2.0.
> chore: Bump minor version

- README.md
- omics/rerun/omics-rerun
- omics/uriparse/uri_parse.py
- tests/uriparse/unit/test_uri_parse.py
*Issue #, if available:*
Adds the omics-rerun tool. 
> Initial commit to add omics-rerun tool.

- pyproject.toml
*Issue #, if available:* n/a
*Description of changes:* bumping release version to 0.3.0
> Increment release version

- README.md
*Description of changes:* Add per-column details for CSV output by `omics-run-analyzer`
> Extend README for omics-run-analyzer

- omics/analyzer/omics-run-analyzer
- poetry.lock
- pyproject.toml
*Issue #, if available: 30
*Description of changes: 
Adds requested cpus/gpus/memory to the omics-analyzer.
> Add requested cpus/gpus/memory to output

- README.md
- omics/cli/run_analyzer/__main__.py
- poetry.lock
- pyproject.toml
*Issue #, if available:*
renames some column names and clarifies their descriptions
> renames some column names and clarifies their descriptions

- pyproject.toml
Bump project version to 0.5.0 ahead of pip release.
> bump version to 0.5.0

- omics/cli/run_analyzer/timeline.py
*Issue #, if available:*
#59 
Changes "queued" terminology to "Starting"
> queud > starting (Correcting terminology)

- pyproject.toml
> bump minor version

- pyproject.toml
> release v0.9.0

- omics/cli/run_analyzer/__main__.py
- omics/cli/run_analyzer/writeconfig.py
- tests/cli/run_analyzer/unit/test_writeconfig.py
*Issue #, if available:* #74
*Description of changes:* Fixes misses config output in recent versions, adds in the `process` block and updates the writeconfig test. 
> fix for config output

- omics/cli/run_analyzer/__main__.py
- omics/cli/run_analyzer/writeconfig.py
fixes formatting of code required by the linter.
> lint fixes

- pyproject.toml
> release v0.10.0

- .gitignore
- omics/cli/run_analyzer/__main__.py
- pyproject.toml
Renames to `aws-healthomics-tools` and bumps version
> Rename pypi package

- omics/cli/run_analyzer/__main__.py
> fixes lint error

- omics/cli/run_analyzer/utils.py
- poetry.lock
Adds the new instance types announced in https://aws.amazon.com/about-aws/whats-new/2025/03/aws-healthomics-workflows-nvidia-l4-l40s-gpus/
> Instance type updates

- pyproject.toml
> version 0.12.0 release

- omics/cli/run_analyzer/__main__.py
> enforces float

- poetry.lock
- pyproject.toml
tornado is a transient dependency of bokeh. updating version due to a vulnerability in tornado.
> update tornado to remove vulnerability

- pyproject.toml
> 0.13 release
